### PR TITLE
 #245 L11 Compatibility 

### LINKED ISSUE #245: Support Laravel 11
**Please describe the problem**
Laravel 11 released.

### PR DESCRIPTION
**Pull request by daikazu**
# Laravel 11 Compatibility

* [x] Closes #245

### CODE REVIEW

**Comment by shankarGdev** [comment]
@MarcinOrlowski Can u plz share an update on this. We are planning to migrate to Laravel 11 and use on new projects.

**Comment by MarcinOrlowski** [comment]
Sorry for lagging with this one - I am bit overloaded. Will do housekeeping in this project over the weekend, so please stay tuned.

**Comment by bnp-angel** [comment]
Do we have any update on this.

**Comment by MarcinOrlowski** [comment]
v11 with L11 support is now out.

https://github.com/MarcinOrlowski/laravel-api-response-builder/releases/tag/v11.0.0

**Pull request closed without merging**
