### PR TITLE
Release v9.3.0

### PR DESCRIPTION
**Pull request by MarcinOrlowski**
* Added `data_always_object` config option that, when enabled enforces response `data` node to always be JSON object (for `NULL` it will return empty object `{}`).
  * Improved code quality (fully pass on PHPStan's strict mode)
  * Fixed floats being rejected as direct primitive payload.
  * Fixed `Converter` unit tests for primitives-as-payload.
  * Fixed `ResponseBuilderProvider` throwing incorrect Exception in case of invalid config file.
  * Added `Validator::assertIsObjectOrExistingClass()` method.
  * `Validator::assertIsInt()` throws now `NotIntegerException` as expected.
  * Corrected `Validator` class tests to check agains specific exceptions thrown, not base class.
  * Improved error handling in `JsonSerializableConverter`
  * Switched Composer's autoload to follow `psr-4` instead of plain `classmap` (thanks to Viktor Szépe).
  * Added `TestingHelpers::getResponseContent()`, `TestingHelpers::langGet()` to satisfy static analyzers.
  * Updated and corrected PHPDocs (incl. some type hints).
  * Added missing type hint to `success()`.
  * Added strict type header to classes.
  * Updated documentation.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Leave those composer.json-s behind and use `composer update "--with=laravel/framework:~6.6"`

**Comment by MarcinOrlowski** [comment]
> You need `"laravel/framework": "^6.0 || ^7.0 || ^8.0"` for that to work.

Not that fast as that's not the only different dependency version I have there. I currently have no time to look for cleaner approaches so this will stay yet for a while. PR welcome though :)

**Comment by szepeviktor** [comment]
Actually these lowest/highest testing could/should be done by Composer.
High: `composer update`
Low: `composer update --prefer-lowest`

**Comment by szepeviktor** [comment]
These .config Composer configuration still contain `classmap` autoloading!

**Comment by MarcinOrlowski** [comment]
> These .config Composer configurations still contain `classmap` autoloading!

Good spot. Fixed. And thanks for taking your time to sniff around!

**Pull request merged**
