### PR TITLE
Use composer update --with...

### PR DESCRIPTION
**Pull request by szepeviktor**
From https://github.com/MarcinOrlowski/laravel-api-response-builder/pull/204#issuecomment-864606443

Sending this to the dev branch!

### CODE REVIEW

**Comment by szepeviktor** [comment]
Please consider running CI on PR-s.

**Comment by szepeviktor** [comment]
Wouldn't it be enough to run unit tests on earliest and latest Laravel 6/7/8 versions?

**Comment by MarcinOrlowski** [comment]
> Wouldn't it be enough to run unit tests on earliest and latest Laravel 6/7/8 versions?

Not sure I got the question - it should run on latest release for each major version using the min. required PHP version.

**Comment by szepeviktor** [comment]
> > Wouldn't it be enough to run unit tests on earliest and latest Laravel 6/7/8 versions?
> 
> Not sure I got the question - it should run on latest release for each major Laravel version using the min. required PHP version for that version.

PHP version would stay. Laravel versions: 6.0, 7.0, 8.0, 6.latest, 7.latest, 8.latest.

Much smaller matrix than the current one.

**Comment by MarcinOrlowski** [comment]
> PHP versions would stay. Laravel versions: 6.0, 7.0, 8.0, 6.latest, 7.latest, 8.latest.

I had separately listed versions as Laravel did not support SemVer for long time. But I think it does starting L6, so perhaps that can be safely changed as you pointed.

**Pull request closed without merging**
